Repository bogyeom0922/EatToday, pull requests merged in 2025-02, with the labels that each got.

#103 Feat: 식당 추천 알고리즘 구현
  .gradle/8.2/checksums/checksums.lock
  .gradle/8.2/checksums/md5-checksums.bin
  .gradle/8.2/checksums/sha1-checksums.bin
  .idea/compiler.xml
  .idea/workspace.xml
  src/main/java/com/eattoday/Eattoday/api/recommendApiController.java
  src/main/java/com/eattoday/Eattoday/dto/LikeDto.java
  src/main/java/com/eattoday/Eattoday/entity/Like.java
  src/main/java/com/eattoday/Eattoday/repository/StoreRepository.java
  src/main/java/com/eattoday/Eattoday/service/LikeService.java
  src/main/java/com/eattoday/Eattoday/service/RecommendationService.java
  src/main/java/com/eattoday/Eattoday/service/StoreService.java
Labels: Backend, Feature

#106 fix: 카테고리 별 카운트 증가 오류 해결
  src/main/java/com/eattoday/Eattoday/recommend/service/RecommendationService.java
Labels: Bug

#108 Refactor: 크롤링 코드 개선 및 불필요한 데이터 제거 #99
  .idea/misc.xml
  .idea/workspace.xml
  scripts/seoul_restaurants_api.py
Labels: Backend, Refactor, Improvement, Bug
